[Instrument] Fix type error in some instruments
When accessing an instrument from RB, I got the error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to ValidatableIdentifier::__construct() must be of the type string, null given, called in
/home/driusan/Code/Loris/php/libraries/NDB_BVL_Instrument.class.inc on line 2863 and defined in /home/driusan/Code/Loris/php/libraries/Valida
tableIdentifier.php:57 Stack trace: #0 /home/driusan/Code/Loris/php/libraries/NDB_BVL_Instrument.class.inc(2863): ValidatableIdentifier->__co
nstruct(NULL) #1 /home/driusan/Code/Loris/src/Middleware/UserPageDecorationMiddleware.php(241): NDB_BVL_Instrument->handle(Object(Laminas\Dia
ctoros\ServerRequest)) #2 /home/driusan/Code/Loris/src/Middleware/PageDecorationMiddleware.php(57): LORIS\Middleware\UserPageDecorationMiddle
ware->process(Object(Laminas\Diactoros\ServerRequest), Object(NDB_BVL_Instrument_aosi)) #3 /home/driusan/Code/Loris/php/libraries/NDB_Page.cl
ass.inc(735): LORIS\Middleware\PageDecorationMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(NDB_BVL_Instrument_aosi)) #4
 /home/driusan/Code/Loris/php/libraries/NDB_BVL_In in /home/driusan/Code/Loris/php/libraries/ValidatableIdentifier.php on line 57
```

This fixes the type error so that the instrument page loads.