[webpack] Update dependencies for latest nodejs (openssl unsupported) (#8184)
Update dependencies for webpack, webpack-cli, and terser-webpack-plugin. Latest nodejs removed openssl causing error when trying to build Loris. Solution to upgrade dependencies. Changes are backwards compatible with current Loris supported version of nodejs.

Solves error:

```
webpack

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);

Error: error:0308010C:digital envelope routines::unsupported
...